### ISSUE TITLE
Vehicle subclasses

### ISSUE THREAD

**Issue by abecede753** [abecede753/trax#7]
As an admin, I want to create more fine grained groups of vehicles for staggered start races.
--

Some classes (e.g. Muscle cars with the Dominator and the Tornado) are too widespread to be used in a staggered start. The fast cars have to wait way too long until they can start racing.

1. An admin is able to create custom vehicle classes out of one official vehicle class, so that only similar vehicles are part of the custom class.

2. These custom classes must be available in the "Host a SSR" screen to be selectable.

**Comment by aryjczyk** [comment]
I made a post on NODO forums describing subclasses in more detail(took me long enough, I know ;p)
I'll link it since I think it's better than just copying the contents http://nodo.freeforums.net/post/234577/thread

**Comment by abecede753** [comment]
Awesome, thank you! I will try to having it implemented on sunday.

**Comment by abecede753** [comment]
I guess, I close this issue now. I don't think it's worth the effort. For staggered start races we always communicate via Teamspeak and the host can just tell people to use cars of a certain group. Furthermore totally restricting the subclass to a few cars can be a little problematic when some folks do not own any of the cars.
