### ISSUE TITLE
Delays caused by people not choosing the car etc.

### ISSUE THREAD

**Issue by aryjczyk** [abecede753/trax#8]
There have been considerable delays caused by people not using the site in SSR playlists. These can't be completely removed, but we can do some things to limit them.
1) Each time SSR playlist is hosted there needs to be post on the forum informing people what they're expected to do
2) When waiting for the race start player list is sorted by pace of their cars atm. Enabling sorting by name would make it easier to determine who's missing.
3)We could play a sound ("Please pick a car" or something like that) to every user who's on the relevant page and didn't pick a car(triggered manually by host)

**Comment by abecede753** [comment]
In fact I did number 1. The second thing is a good idea. Will implement this. The third one is even better :-D

**Comment by abecede753** [comment]
I think I found an unintrusive but nevertheless effective solution. Every driver is listed in the "registered drivers" list regardless whether he chose a car already or not. (if he did not choose a car yet, the sting "WAITING..." is displayed in his vehicle column)
