### ISSUE TITLE
Cannot pick a car in a SSR

### ISSUE THREAD

**Issue by aryjczyk** [abecede753/trax#9]
On the first race today after entering the playlist's subpage I was able to see the list of cars, but clicking on them did nothing. There was my name in the top right as if I was logged in. Ctrl+F5 sent me to login screen, everything worked fine after I logged in. Someone else had the same issue as well, he was using Chrome and I used Firefox, so it doesn't appear to be browser related. Maybe the race subpage doesn't check login status when you enter it?

**Comment by abecede753** [comment]
Maybe it has to do with some caching on the server. The web site does not show the car-selection screen unless you are logged in. I'll examine further. Thanks a lot for the info!

**Comment by abecede753** [comment]
Could not reproduce anymore. Hope the bug left the area.
